# Generated by Django 4.2.2 on 2023-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_peto_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='peto',
            name='bio',
            field=models.CharField(default='i love fish!!', max_length=1000),
            preserve_default=False,
        ),
    ]
