# Generated by Django 4.1.7 on 2023-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pet_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
