# Generated by Django 4.1.7 on 2023-04-03 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 8, 15, 35, 845306, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pet_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
