# Generated by Django 4.2.2 on 2023-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=20)),
                ('vet_calendly', models.CharField(max_length=200)),
                ('vet_description', models.CharField(max_length=2000)),
                ('vet_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
