# Generated by Django 4.2.2 on 2023-06-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_vets_vet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vets',
            name='temp',
            field=models.CharField(default='awaz', max_length=20),
            preserve_default=False,
        ),
    ]
