# Generated by Django 4.2.2 on 2023-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_rename_temp_vets_temp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vets',
            name='vet_name',
            field=models.CharField(default='awaz', max_length=30),
            preserve_default=False,
        ),
    ]
