# Generated by Django 4.2.2 on 2023-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_vets_vet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vets',
            name='temp_name',
        ),
        migrations.AlterField(
            model_name='vets',
            name='vet_name',
            field=models.CharField(max_length=20),
        ),
    ]
