# Generated by Django 4.2.2 on 2023-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_remove_vets_temp_name_alter_vets_vet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vets',
            name='vet_email',
            field=models.EmailField(max_length=200),
        ),
    ]
