# Generated by Django 4.2.2 on 2023-07-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_vets_vet_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vets',
            name='vet_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vets',
            name='vet_email',
            field=models.EmailField(max_length=254),
        ),
    ]
